# Generated by Django 6.0.5 on 2026-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plaintes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='type',
            field=models.CharField(choices=[('mairie', 'Mairie'), ('entreprise', 'Entreprise'), ('service_public', 'Service Public'), ('environnement', 'Environnement'), ('securite', 'Sécurité'), ('autre', 'Autre')], default='autre', max_length=50),
        ),
    ]
